name: A workflow to check for rc packages
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
    paths:
    - '/package.json'
jobs:
  rc-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checks this action for errors
        uses: actions/checkout@v1
      - name: check for rc packages
        uses: ./action
